app:
  env: compose
log:
  level: debug
  file: /app/logs/app.log
swagger:
  enabled: true
database:
  name: platform
  schema: tenant
grpc:
  reflection_enabled: true
cron:
  enabled: true
event_bus:
  enabled: true
  urls: [nats://nats:4222]
